[package]
name = "pomoxide"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.0.17"
clap = { version = "4.5.37", features = ["derive"] }
indicatif = "0.17.11"
predicates = "3.1.3"
time = { version = "0.3.41", features = ["formatting", "local-offset", "parsing"] }
timer = "0.2.0"
