[package]
name = "pomoxide"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.0.17"
chrono = "0.4.40"
clap = { version = "4.5.37", features = ["derive"] }
indicatif = "0.17.11"
predicates = "3.1.3"
timer = "0.2.0"
